config/routes.rb
Rails.application.routes.draw do

  get 'apply/question'

  root 'static_pages#home'

  get 'home' => 'static_pages#home'
  get 'homie' => 'static_pages#homie'
  get 'result' => 'static_pages#result'

  resources :sessions, only: [:new, :create, :destroy, :show] do
    member do
      get 'question/:question_id' => 'questions#show_form', as: :question 
      post 'question/:question_id/answer' => 'answers#create', as: :answer
      patch 'question/:question_id/edit_answer' => 'answers#update', as: :edit_answer
      get 'result' => 'questions#view_result', as: :result
    end
  end 

  get 'sessions/apply_form'

  resources :submit_questions
  resources :questions do
    resources :choices
  end

 

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :session
  belongs_to :question
end

app/models/choice.rb
class Choice < ActiveRecord::Base
	belongs_to :question
	validates :BrA, presence: true
	validates :BrB, presence: true
	validates :BrC, presence: true
	validates :BrD, presence: true
	validates :BrE1, presence: true
	validates :BrE2, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :choices
	has_one :answer
	validates :question_body, presence: true
    
	def Question.random_question
		@randarray = Array.new(10)
		(1..10).each do |i|
			@randnum = rand(Question.all.length) + Question.first.id
			while Question.all.length >= 10 and @randarray.detect {|j| j == @randnum } do
				@randnum = rand(Question.all.length) + Question.first.id
			end
			@randarray[i-1] = @randnum
		end

		return @randarray
	end

end

app/models/session.rb
class Session < ActiveRecord::Base
  has_many :questions
  has_many :answers, dependent: :destroy
  serialize :questionIDs
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @session = Session.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.pick = params["question_#{@question.id.to_s}"].to_i
    @answer.question_id = @question.id
    @answer.session_id = @session.id
    @answer.save
    #binding.pry
    redirect_to question_session_path(@session, @question)
  end

  def update
    @session = Session.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer = Answer.find(@question.answer.id)
    @answer.pick = params["question_#{@question.id.to_s}"].to_i
    @answer.save
    binding.pry
    redirect_to question_session_path(@session, @question) 
  end
  private
    def answer_params
      params.require(:answer).permit(:question_id, :id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController
  
  def new
    @session = Session.find(params[:id])
  end

  def question
  	@session = Session.find(params[@session.id])
  end

  def show
  	@session.questions[0].show
  end
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
	def new
		@question = Question.find(params[:question_id])
		@choice = @question.choices.new
	end

	def create
		@question = Question.find(params[:question_id])
		@choice = @question.choices.create(choice_params)
		redirect_to @question
	end
=begin
	def show

		@choice = Choice.find(paras[:id])
	end
=end
	private
		def choice_params
			params.require(:choice).permit(:BrA, :BrB, :BrC, :BrD, :BrE1, :BrE2)
		end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.save
    redirect_to @question
  end

  def index
  end

  def show
    @question = Question.find(params[:id])
    #@randquestion = Question.random_question #<-- Array of Question IDs
  end

  def show_form
    @session = Session.find(params[:id])
    @question = Question.find(params[:question_id])
    @choice = @question.choices.find(params[:question_id])

    #@randquestion = Question.random_question
=begin
    @show_question_array = Array.new(10)
    (1..10).each do |i|
      @show_question_array[i-1] = @session.questions[i-1].id
    end
=end
  end

  def view_result

    @tally = {BracketA: 0, BracketB: 0, BracketC: 0, BracketD: 0, BracketE1: 0, BracketE2: 0}
    @session = Session.find(params[:id])
    @session.answers.each do |answer|
      if answer.pick == 1
        @tally[:BracketA] += 1
      elsif answer.pick == 2
        @tally[:BracketB] += 1
      elsif answer.pick == 3
        @tally[:BracketC] += 1
      elsif answer.pick == 4
        @tally[:BracketD] += 1
      elsif answer.pick == 5
        @tally[:BracketE1] += 1
      elsif answer.pick == 6
        @tally[:BracketE2] += 1
      end  
    end
    @session.destroy
    binding.pry
  end

  private
    def question_params
      params.require(:question).permit(:question_body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    if Question.all.length >= 10
      @session = Session.new

      @questionIDs = Question.random_question
      @session.questionIDs = @questionIDs
      #binding.pry
      @questionList = Array.new(10)
      (1..10).each do |i|
        @questionList[i-1] = Question.find(@questionIDs[i-1])
      end

      @session.questions = @questionList

      @session.save
      

      redirect_to question_session_path(@session, @session.questionIDs[0])
    else
      redirect_to new_question_path
    end
  end

  def show
    @session = Session.find(params[:id])
    #binding.pry
  end

  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	Session.destroy_all
  end

  def result
  end
end

app/controllers/submit_questions_controller.rb
class SubmitQuestionsController < ApplicationController
	def new
	end

	def create
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apply_helper.rb
module ApplyHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def full_title(title)
    main_title = 'STSucks'
    if title
      "#{main_title} | #{title}"
    else
      main_title
    end
  end
end

app/helpers/submit_questions_helper.rb
module SubmitQuestionsHelper
end

app/views/apply/question.html.erb
<%= @session.questions[0].question_body %>

app/views/choices/_choice.html.erb
<% if @question.choices %>
	<% @question.choices.each do |choice| %>
	   <br>
		Bracket A: <%= choice.BrA %><br>
		Bracket B: <%= choice.BrB %><br>
		Bracket C: <%= choice.BrC %><br>
		Bracket D: <%= choice.BrD %><br>
		Bracket E1: <%= choice.BrE1 %><br>
		Bracket E2: <%= choice.BrE2 %><br>
	<% end %>
<% end %>

app/views/choices/_form.html.erb
<% if !@question.choices.any? %>
	<%= form_for :choice, url: question_choices_path(@question) do |f| %>
		<p>
			Enter choices:
			<br>
			&nbsp; &nbsp; Bracket A: 
			<br>
			&nbsp; &nbsp; <%= f.text_field :BrA %>
			<br>
			&nbsp; &nbsp; Bracket B: 
			<br>
			&nbsp; &nbsp; <%= f.text_field :BrB %>
			<br>
			&nbsp; &nbsp; Bracket C: 
			<br>
			&nbsp; &nbsp; <%= f.text_field :BrC %>
			<br>
			&nbsp; &nbsp; Bracket D: 
			<br>
			&nbsp; &nbsp; <%= f.text_field :BrD %>
			<br>
			&nbsp; &nbsp; Bracket E1: 
			<br>
			&nbsp; &nbsp; <%= f.text_field :BrE1 %>
			<br>
			&nbsp; &nbsp; Bracket E2: 
			<br>
			&nbsp; &nbsp; <%= f.text_field :BrE2 %>
		</p>

		<p>
			<%= f.submit  'Submit', class: 'btn btn-warning btn-lg' %>
		</p>

	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for :question, url: questions_path do |f| %>
	<p>
		Enter Question here:
		<br>
		<%= f.text_area :question_body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<%#= render 'choices/form' %>

app/views/questions/new.html.erb
<%= form_for :question, url: questions_path do |f| %>
  <div class="submit_question_bilog"  >
    
    <div id="submit_question_title">
      <strong>STS</strong> Submit a Question
    </div>
          
    <hr>
    
    <p>Enter Question Here:<br><%= f.text_area :question_body %></p>
    
    <p>
      <%= link_to 'Cancel', homie_path , class: 'btn btn-info btn-lg'%>  
      <%= f.submit  'Submit', class: 'btn btn-warning btn-lg' %>
    </p>

  </div>

<% end %>

<%#= render 'choices/form' %>

app/views/questions/show.html.erb
<div class = "page_margins">
	<div class = "choices_box">
		<div id="submit_question_title">
      		<strong>STS</strong> Submit a Question
    	</div>

    	<hr>
    	Question:<br>
		&nbsp; &nbsp; <%= @question.question_body %>

		<%= render 'choices/form' %>

		<%= render 'choices/choice' %>
	</div>
</div>


<%# (0..9).each do |i| %>
	<%#= Question.find(@randquestion[i]).question_body %><br>
<%# end %>

app/views/questions/show_form.html.erb
<% index = 0 %>
<% (1..10).each do |i| %>
  <% if @question.id == @session.questionIDs[i-1] %>
    <% index = i %>
  <% end %>
<% end %>

<%= @question.question_body %>
<br>
<% unless @question.answer.nil? %>
  <%= form_tag({controller: 'answers', action: 'update'}, method: :patch) do %>
    <% if @question.answer.pick == 1 %>
      <%= radio_button_tag("question_#{@question.id.to_s}", "1", checked: :checked) %>
      <%= label_tag(:BracketA, @choice.BrA) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "2") %>
      <%= label_tag(:BracketB, @choice.BrB) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "3") %>
      <%= label_tag(:BracketC, @choice.BrC) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "4") %>
      <%= label_tag(:BracketD, @choice.BrD) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "5") %>
      <%= label_tag(:BracketE1, @choice.BrE1) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "6") %>
      <%= label_tag(:BracketE2, @choice.BrE2) %>
      <br>
    <% elsif @question.answer.pick == 2 %>
      <%= radio_button_tag("question_#{@question.id.to_s}", "1") %>
      <%= label_tag(:BracketA, @choice.BrA) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "2", checked: :checked) %>
      <%= label_tag(:BracketB, @choice.BrB) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "3") %>
      <%= label_tag(:BracketC, @choice.BrC) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "4") %>
      <%= label_tag(:BracketD, @choice.BrD) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "5") %>
      <%= label_tag(:BracketE1, @choice.BrE1) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "6") %>
      <%= label_tag(:BracketE2, @choice.BrE2) %>
      <br>
    <% elsif @question.answer.pick == 3 %>
      <%= radio_button_tag("question_#{@question.id.to_s}", "1") %>
      <%= label_tag(:BracketA, @choice.BrA) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "2") %>
      <%= label_tag(:BracketB, @choice.BrB) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "3", checked: :checked) %>
      <%= label_tag(:BracketC, @choice.BrC) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "4") %>
      <%= label_tag(:BracketD, @choice.BrD) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "5") %>
      <%= label_tag(:BracketE1, @choice.BrE1) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "6") %>
      <%= label_tag(:BracketE2, @choice.BrE2) %>
      <br>
    <% elsif @question.answer.pick == 4 %>
      <%= radio_button_tag("question_#{@question.id.to_s}", "1") %>
      <%= label_tag(:BracketA, @choice.BrA) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "2") %>
      <%= label_tag(:BracketB, @choice.BrB) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "3") %>
      <%= label_tag(:BracketC, @choice.BrC) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "4", checked: :checked) %>
      <%= label_tag(:BracketD, @choice.BrD) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "5") %>
      <%= label_tag(:BracketE1, @choice.BrE1) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "6") %>
      <%= label_tag(:BracketE2, @choice.BrE2) %>
      <br>
    <% elsif @question.answer.pick == 5 %>
      <%= radio_button_tag("question_#{@question.id.to_s}", "1") %>
      <%= label_tag(:BracketA, @choice.BrA) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "2") %>
      <%= label_tag(:BracketB, @choice.BrB) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "3") %>
      <%= label_tag(:BracketC, @choice.BrC) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "4") %>
      <%= label_tag(:BracketD, @choice.BrD) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "5", checked: :checked) %>
      <%= label_tag(:BracketE1, @choice.BrE1) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "6") %>
      <%= label_tag(:BracketE2, @choice.BrE2) %>
      <br>
    <% elsif @question.answer.pick == 6 %>
      <%= radio_button_tag("question_#{@question.id.to_s}", "1") %>
      <%= label_tag(:BracketA, @choice.BrA) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "2") %>
      <%= label_tag(:BracketB, @choice.BrB) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "3") %>
      <%= label_tag(:BracketC, @choice.BrC) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "4") %>
      <%= label_tag(:BracketD, @choice.BrD) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "5") %>
      <%= label_tag(:BracketE1, @choice.BrE1) %>
      <br>
      <%= radio_button_tag("question_#{@question.id.to_s}", "6", checked: :checked) %>
      <%= label_tag(:BracketE2, @choice.BrE2) %>
      <br>
    <% end %>
    <%= submit_tag("Edit Answer") %>
  <% end %>
<% else %>
  <%= form_tag({controller: 'answers', action: 'create'}, method: :post) do %>
    <%= radio_button_tag("question_#{@question.id.to_s}", "1") %>
    <%= label_tag(:BracketA, @choice.BrA) %>
    <br>
    <%= radio_button_tag("question_#{@question.id.to_s}", "2") %>
    <%= label_tag(:BracketB, @choice.BrB) %>
    <br>
    <%= radio_button_tag("question_#{@question.id.to_s}", "3") %>
    <%= label_tag(:BracketC, @choice.BrC) %>
    <br>
    <%= radio_button_tag("question_#{@question.id.to_s}", "4") %>
    <%= label_tag(:BracketD, @choice.BrD) %>
    <br>
    <%= radio_button_tag("question_#{@question.id.to_s}", "5") %>
    <%= label_tag(:BracketE1, @choice.BrE1) %>
    <br>
    <%= radio_button_tag("question_#{@question.id.to_s}", "6") %>
    <%= label_tag(:BracketE2, @choice.BrE2) %>
    <br>
    <%= submit_tag("Save Answer") %>
  <% end %>
<% end %>

<% unless @question.answer.nil? %>
  Your Answer: 
  <% if @question.answer.pick == 1 %>
    <%= @question.choices[0].BrA %>
  <% elsif @question.answer.pick == 2 %>
    <%= @question.choices[0].BrB %>
  <% elsif @question.answer.pick == 3 %>
    <%= @question.choices[0].BrC %>
  <% elsif @question.answer.pick == 4 %>
    <%= @question.choices[0].BrD %>
  <% elsif @question.answer.pick == 5 %>
    <%= @question.choices[0].BrE1 %>
  <% elsif @question.answer.pick == 6 %>
    <%= @question.choices[0].BrE2 %>
  <% end %>
<% end %>
<br>

<% if index == 10 %>
  <%= link_to 'View Results', result_session_path(@session) %>
<% else %>
  <%= link_to 'Next', question_session_path(@session, @session.questionIDs[index]) %>
<% end %>

app/views/questions/view_result.html.erb
Bracket A: <%= @tally[:BracketA] %><br>
Bracket B: <%= @tally[:BracketB] %><br>
Bracket C: <%= @tally[:BracketC] %><br>
Bracket D: <%= @tally[:BracketD] %><br>
Bracket E1: <%= @tally[:BracketE1] %><br>
Bracket E2: <%= @tally[:BracketE2] %><br>

app/views/shared/_form_questions.html.erb
<%= form_for :question, url: questions_path do |f| %>
	<p>
		Enter Question here:
		<br>
		<%= f.text_area :question_body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<%#= render 'choices/form' %>

app/views/static_pages/home.html.erb
<% content_for :title, 'Home' %>
<br><br><br><br><br><br><br>
<div class="container" id="homepage_container">
  <div class="row" id="home">

    <div class="col-lg-6 col-lg-offset-3 centerfy">
      <div class="jumbotron" id="homepage_jumbotron">
        
        <div id="STS">
          <strong><h1>STS</h1></strong>
        </div>
        <p><%= link_to 'Apply now!', sessions_path, method: :post, class: 'btn btn-danger btn-lg'%></p>
        <p>Want to add a question? <br><%= link_to 'Submit one now!!!', new_question_path %></p>
        Developed by: Bukluran Team
      </div>
    </div>
  </div>
</div>

app/views/static_pages/homie.html.erb
<% content_for :title, 'Home' %>
<!-- <br><br><br><br> -->
<div id="circle_background">
  <img />
  <br><br>
  <div id="sts_heading">
    <h1><strong>STS</strong></h1>
  </div>

  <div id="sts_details">
    <p><%= link_to 'Apply now!', sessions_apply_form_path , class: 'btn btn-warning btn-lg'%></p>
    <p> &nbsp Want to add a question? <br> &nbsp <%= link_to 'Submit one now!!!', new_question_path %></p>
    &nbsp Developed by: Bukluran Team
  </div>

</div>

app/views/static_pages/result.html.erb
<% content_for :title, 'GGWP' %>
<div class="container">
  <div class = "page_margins">
      <div class="result_circle">
        <div class = "center-block">
          <div class = "bracket_row">
            <h1><strong>BRACKET</strong></h1>
          </div>
          <div class = "bracket_letter">
            <h2><strong>A</strong></h2>
          </div>
          <p>
            Because you like anime.
          </p> 
        </div>
      </div>
  </div>
</div>